version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/backend
      REDIS_URL: redis://redis:6379/0
    networks:
      - backend-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    networks:
      - backend-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - backend-network

  worker:
    build: .
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/backend
      REDIS_URL: redis://redis:6379/0
    command: python worker.py
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
